import React, { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import {
  Building2,
  Handshake,
  ArrowLeft,
  Calendar,
  MapPin,
  TrendingUp,
  Receipt,
  HardHat,
  Package,
  Landmark,
  FileSpreadsheet,
  Printer,
  Share2,
  Percent,
  CheckCircle,
  Plus,
  BookmarkCheck,
  Phone,
  User,
  Filter,
  Edit3,
  Trash2
} from 'lucide-react';
import { projectsAPI } from '../../services/api';
import { formatNPR, amountInWords } from '../../utils/helpers';
import { formatBSDate, getFiscalYear, getFiscalYearList } from '../../utils/nepaliDate';
import { useCompany } from '../../contexts/CompanyContext';
import Loader from '../../components/ui/Loader';
import Modal from '../../components/ui/Modal';
import toast from 'react-hot-toast';

export default function ProjectDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { company } = useCompany();
  const [project, setProject] = useState(null);
  const [summary, setSummary] = useState(null);
  const [expenses, setExpenses] = useState([]);
  const [siteLedger, setSiteLedger] = useState(null);
  const [selectedFY, setSelectedFY] = useState('');
  const [activeTab, setActiveTab] = useState('ledger'); // 'ledger' | 'overview' | 'expenses'
  const [loading, setLoading] = useState(true);

  // Edit Site Modal State
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [editForm, setEditForm] = useState(null);
  const [savingEdit, setSavingEdit] = useState(false);

  const fiscalYears = getFiscalYearList();

  const loadData = async () => {
    try {
      setLoading(true);
      const [pRes, sRes, eRes, lRes] = await Promise.all([
        projectsAPI.getById(id),
        projectsAPI.getSummary(id),
        projectsAPI.getExpenses(id, { fiscal_year: selectedFY || undefined }),
        projectsAPI.getLedger(id, { fiscal_year: selectedFY || undefined }),
      ]);
      setProject(pRes.data.data);
      setSummary(sRes.data.data);
      setExpenses(eRes.data.data || []);
      setSiteLedger(lRes.data.data || null);
    } catch (err) {
      toast.error('Failed to load site details');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [id, selectedFY]);

  if (loading) return <Loader text="Loading site ledger & financial data..." />;
  if (!project) return <div className="p-8 text-center text-slate-400">Site not found.</div>;

  const isJV = project.project_type === 'joint_venture';
  const spent = summary?.total_spent || 0;
  const budget = parseFloat(project.budget_total) || 0;
  const contractVal = parseFloat(project.contract_value) || 0;
  const remaining = budget - spent;
  const percentUsed = budget > 0 ? Math.min(Math.round((spent / budget) * 100), 100) : 0;

  // JV Profit calculation
  const grossMargin = contractVal - spent;
  const rpSharePercent = project.rp_share_percent || 100;
  const partnerSharePercent = project.partner_share_percent || 0;
  const rpProfitShare = (grossMargin * rpSharePercent) / 100;
  const partnerProfitShare = (grossMargin * partnerSharePercent) / 100;

  const handleCopyWhatsAppSummary = () => {
    const text = `🏗️ *R.P. BUILDERS PVT. LTD. — SITE SUMMARY*
Site: *${project.project_name}* (${project.project_code})
Type: ${isJV ? `Joint Venture (Partner: ${project.partner_company_name})` : 'Solo (100% RP Builders)'}
Start Date: ${project.start_date_bs} BS
----------------------------
💰 Contract Value: ${formatNPR(contractVal)}
📊 Total Spent: ${formatNPR(spent)}
📉 Budget Remaining: ${formatNPR(remaining)}
${isJV ? `🤝 RP Profit Share (${rpSharePercent}%): ${formatNPR(rpProfitShare)}\n🤝 Partner Share (${partnerSharePercent}%): ${formatNPR(partnerProfitShare)}` : `📈 Estimated Margin: ${formatNPR(grossMargin)}`}
----------------------------
Report generated by Nirmala Tech ERP`;

    navigator.clipboard.writeText(text);
    toast.success('Site summary copied! You can now paste and send it on WhatsApp.');
  };

  const handleOpenEdit = () => {
    setEditForm({
      project_name: project.project_name || '',
      project_name_np: project.project_name_np || '',
      project_type: project.project_type || 'solo',
      partner_company_name: project.partner_company_name || '',
      rp_share_percent: String(project.rp_share_percent || 60),
      partner_share_percent: String(project.partner_share_percent || 40),
      main_client_name: project.main_client_name || '',
      main_client_phone: project.main_client_phone || '',
      site_address: project.site_address || '',
      site_district: project.site_district || 'Kathmandu',
      contract_value: project.contract_value ? String(project.contract_value) : '',
      budget_total: project.budget_total ? String(project.budget_total) : '',
      start_date_bs: project.start_date_bs || '',
      status: project.status || 'active',
      description: project.description || '',
    });
    setIsEditModalOpen(true);
  };

  const handleSaveEdit = async (e) => {
    e.preventDefault();
    try {
      setSavingEdit(true);
      const payload = {
        ...editForm,
        contract_value: parseFloat(editForm.contract_value) || 0,
        budget_total: parseFloat(editForm.budget_total) || 0,
        rp_share_percent: editForm.project_type === 'joint_venture' ? parseFloat(editForm.rp_share_percent) || 50 : 100,
        partner_share_percent: editForm.project_type === 'joint_venture' ? parseFloat(editForm.partner_share_percent) || 50 : 0,
      };

      const res = await projectsAPI.update(id, payload);
      if (res.data.success) {
        toast.success(`साइट "${editForm.project_name}" विवरण अद्यावधिक गरियो!`);
        setIsEditModalOpen(false);
        loadData();
      }
    } catch (err) {
      toast.error(err?.response?.data?.message || 'Failed to update site');
    } finally {
      setSavingEdit(false);
    }
  };

  const handleDeleteSite = async () => {
    if (!window.confirm(`के तपाईं "${project.project_name}" (${project.project_code}) साइट मेटाउन निश्चित हुनुहुन्छ?`)) {
      return;
    }

    try {
      const res = await projectsAPI.delete(id);
      if (res.data.success) {
        toast.success(res.data.message);
        navigate('/projects');
      }
    } catch (err) {
      const msg = err?.response?.data?.message || 'Failed to delete site';
      if (err?.response?.status === 400 && window.confirm(`${msg}\n\nके तपाईं यस साइट र यसका सबै भौचरहरू जबरजस्ती मेटाउन चाहनुहुन्छ? (Force Delete)`)) {
        try {
          const forceRes = await projectsAPI.delete(id, true);
          if (forceRes.data.success) {
            toast.success('साइट र सम्बन्धित भौचरहरू सफलतापूर्वक मेटाइयो');
            navigate('/projects');
          }
        } catch (forceErr) {
          toast.error(forceErr?.response?.data?.message || 'Force delete failed');
        }
      } else {
        toast.error(msg);
      }
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 no-print">
        <div className="flex items-center gap-3">
          <Link
            to="/projects"
            className="p-2 rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-100 transition"
          >
            <ArrowLeft className="w-4 h-4" />
          </Link>
          <div>
            <div className="flex items-center gap-2">
              <span className="font-mono text-xs font-black px-2 py-0.5 rounded bg-white border border-slate-200 text-slate-700">
                {project.project_code}
              </span>
              <span className={`text-xs font-black px-2.5 py-0.5 rounded-full uppercase ${
                isJV ? 'bg-purple-100 text-purple-800' : 'bg-blue-100 text-blue-800'
              }`}>
                {isJV ? '🤝 Joint Venture (JV)' : '🏛️ Solo Site'}
              </span>
              <span className="text-[10px] font-bold px-2 py-0.5 rounded uppercase bg-emerald-100 text-emerald-800">
                {project.status}
              </span>
            </div>
            <h2 className="text-xl font-black text-slate-900 mt-1">{project.project_name}</h2>
          </div>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          {/* Fiscal Year Filter */}
          <select
            value={selectedFY}
            onChange={(e) => setSelectedFY(e.target.value)}
            className="px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-bold text-slate-800 outline-none"
          >
            <option value="">सबै आ.व. (All Fiscal Years)</option>
            {fiscalYears.map((fy, i) => (
              <option key={i} value={fy.value}>{fy.label}</option>
            ))}
          </select>

          <button
            onClick={handleCopyWhatsAppSummary}
            className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold shadow-sm transition cursor-pointer"
          >
            <Share2 className="w-4 h-4" />
            <span>WhatsApp Summary</span>
          </button>

          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-slate-900 text-white rounded-xl text-xs font-bold shadow-sm transition cursor-pointer"
          >
            <Printer className="w-4 h-4" />
            <span>Print Site Ledger</span>
          </button>

          <button
            onClick={handleOpenEdit}
            className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-amber-500 hover:bg-amber-600 text-white rounded-xl text-xs font-bold shadow-sm transition cursor-pointer"
          >
            <Edit3 className="w-4 h-4" />
            <span>साइट सम्पादन (Edit)</span>
          </button>

          <button
            onClick={handleDeleteSite}
            className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-red-600 hover:bg-red-700 text-white rounded-xl text-xs font-bold shadow-sm transition cursor-pointer"
          >
            <Trash2 className="w-4 h-4" />
            <span>मेटाउनुहोस् (Delete)</span>
          </button>

          <Link
            to="/vouchers/entry"
            className="inline-flex items-center gap-1.5 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold shadow-md shadow-blue-600/20 transition cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>खर्च इन्ट्री</span>
          </Link>
        </div>
      </div>

      {/* 4 Summary Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 no-print">
        <div className="bg-white p-5 rounded-3xl border border-slate-200/90 shadow-xs">
          <span className="text-[11px] font-bold text-slate-500 block">ठेक्का रकम (Contract Value)</span>
          <span className="text-lg font-black font-mono text-slate-900 mt-1 block">
            {formatNPR(contractVal)}
          </span>
          <span className="text-[10px] text-slate-400">Total client agreed billing</span>
        </div>

        <div className="bg-white p-5 rounded-3xl border border-slate-200/90 shadow-xs">
          <span className="text-[11px] font-bold text-slate-500 block">स्वीकृत बजेट (Estimated Budget)</span>
          <span className="text-lg font-black font-mono text-blue-700 mt-1 block">
            {formatNPR(budget)}
          </span>
          <span className="text-[10px] text-slate-400">Site expense ceiling</span>
        </div>

        <div className="bg-white p-5 rounded-3xl border border-slate-200/90 shadow-xs">
          <span className="text-[11px] font-bold text-slate-500 block">हालसम्मको खर्च (Total Spent)</span>
          <span className="text-lg font-black font-mono text-red-600 mt-1 block">
            {formatNPR(spent)}
          </span>
          <span className="text-[10px] font-bold text-red-600/80">{percentUsed}% Budget Used</span>
        </div>

        <div className="bg-white p-5 rounded-3xl border border-slate-200/90 shadow-xs">
          <span className="text-[11px] font-bold text-slate-500 block">बाँकी बजेट (Remaining Budget)</span>
          <span className={`text-lg font-black font-mono mt-1 block ${remaining >= 0 ? 'text-emerald-600' : 'text-red-600'}`}>
            {formatNPR(remaining)}
          </span>
          <span className="text-[10px] text-slate-400">{remaining >= 0 ? 'Budget on track' : 'Over budget'}</span>
        </div>
      </div>

      {/* Joint Venture Partner Box (If JV) */}
      {isJV && (
        <div className="bg-gradient-to-r from-purple-900 to-indigo-900 text-white rounded-3xl p-6 shadow-md space-y-4 no-print">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-purple-800 pb-3 gap-2">
            <div className="flex items-center gap-2.5">
              <Handshake className="w-6 h-6 text-purple-300" />
              <div>
                <h3 className="font-black text-sm text-white">
                  Joint Venture (JV) Partnership & Profit Allocation (साझेदारी नाफा बाँडफाँड)
                </h3>
                <p className="text-[11px] text-purple-200">
                  Partner: <strong className="text-white">{project.partner_company_name}</strong> • Ratio: {rpSharePercent}% RP : {partnerSharePercent}% Partner
                </p>
              </div>
            </div>

            <div className="text-right">
              <span className="text-[10px] text-purple-300 block">Estimated Site Net Profit:</span>
              <span className="font-mono text-lg font-black text-emerald-400">
                {formatNPR(grossMargin)}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="p-4 bg-white/10 backdrop-blur-xs rounded-2xl border border-white/10">
              <div className="flex justify-between items-center mb-1">
                <span className="text-xs font-bold text-purple-200">🏛️ R.P. Builders Share ({rpSharePercent}%):</span>
                <span className="font-mono text-base font-black text-white">{formatNPR(rpProfitShare)}</span>
              </div>
              <p className="text-[10px] text-purple-300">Net profit entitlement to R.P. Builders Pvt. Ltd.</p>
            </div>

            <div className="p-4 bg-white/10 backdrop-blur-xs rounded-2xl border border-white/10">
              <div className="flex justify-between items-center mb-1">
                <span className="text-xs font-bold text-purple-200">🤝 Partner Share ({partnerSharePercent}%):</span>
                <span className="font-mono text-base font-black text-purple-200">{formatNPR(partnerProfitShare)}</span>
              </div>
              <p className="text-[10px] text-purple-300">Net profit entitlement to {project.partner_company_name}</p>
            </div>
          </div>
        </div>
      )}

      {/* Tabs Menu */}
      <div className="flex items-center gap-2 border-b border-slate-200 pb-3 no-print">
        <button
          onClick={() => setActiveTab('ledger')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition cursor-pointer ${
            activeTab === 'ledger'
              ? 'bg-blue-600 text-white shadow-sm'
              : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
          }`}
        >
          📖 साइट खाता (Site Ledger)
        </button>

        <button
          onClick={() => setActiveTab('overview')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition cursor-pointer ${
            activeTab === 'overview'
              ? 'bg-blue-600 text-white shadow-sm'
              : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
          }`}
        >
          ℹ️ साइट विवरण (Site Overview)
        </button>
      </div>

      {/* Printable Report Header */}
      <div className="hidden print:block text-center border-b-2 border-slate-800 pb-4 mb-4">
        {company?.company_logo_data ? (
          <img
            src={company.company_logo_data}
            alt={company?.company_name || 'Logo'}
            className="h-16 max-w-[200px] object-contain mx-auto mb-2"
          />
        ) : (
          <h2 className="text-2xl font-black uppercase text-slate-900 tracking-tight">
            {company?.company_name || 'R.P. BUILDERS PVT. LTD.'}
          </h2>
        )}
        <h2 className="text-xl font-black uppercase text-slate-900 tracking-tight">
          {company?.company_name || 'R.P. BUILDERS PVT. LTD.'}
        </h2>
        <p className="text-xs text-slate-600">{company?.address || 'Nepal'} • Construction Site Account Ledger • PAN: {company?.pan_no || '600123456'}</p>
        <h3 className="text-lg font-bold mt-2 underline">
          साइट लेजर खाता (SITE ACCOUNT LEDGER): {project.project_name}
        </h3>
        <div className="flex justify-between text-xs mt-2 font-medium">
          <span>Project Code: <strong>{project.project_code}</strong></span>
          <span>Contract Value: <strong>{formatNPR(contractVal)}</strong></span>
          <span>Budget: <strong>{formatNPR(budget)}</strong></span>
          <span>आ.व.: <strong>{selectedFY || 'All'}</strong></span>
        </div>
      </div>

      {/* Tab: Site Ledger */}
      {activeTab === 'ledger' && (
        <div className="bg-white rounded-3xl border border-slate-200/90 shadow-xs overflow-hidden">
          <div className="p-4 sm:p-5 border-b border-slate-100 flex items-center justify-between no-print">
            <h3 className="font-black text-sm text-slate-900">
              साइट सम्पूर्ण आय-व्यय खाता (Itemized Site Ledger)
            </h3>
            <span className="text-xs text-slate-500 font-bold">
              Total Transactions: {siteLedger?.transactions?.length || 0}
            </span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 uppercase font-black text-[10px] tracking-wider">
                  <th className="py-3 px-3">S.N.</th>
                  <th className="py-3 px-3">मिति (Date BS)</th>
                  <th className="py-3 px-3">भौचर नं.</th>
                  <th className="py-3 px-3">पार्टी / सप्लायर्स (Party)</th>
                  <th className="py-3 px-3">शीर्षक तथा विवरण (Description)</th>
                  <th className="py-3 px-3">माध्यम / बुझ्ने व्यक्तिको नाम</th>
                  <th className="py-3 px-3 text-right">खर्च (Expense)</th>
                  <th className="py-3 px-3 text-right">कुल खर्च (Running Total)</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {siteLedger?.transactions?.map((t, index) => (
                  <tr key={t.id} className="hover:bg-slate-50/80 transition">
                    <td className="py-3 px-3 text-slate-400 font-mono text-[11px]">{index + 1}</td>
                    <td className="py-3 px-3 font-mono font-bold text-slate-700 whitespace-nowrap">
                      {t.voucher_date_bs}
                    </td>
                    <td className="py-3 px-3 font-mono font-bold text-blue-700 whitespace-nowrap">
                      {t.voucher_no}
                    </td>
                    <td className="py-3 px-3 font-bold text-slate-900">
                      {t.party_name || '—'}
                    </td>
                    <td className="py-3 px-3 max-w-xs">
                      <div className="font-bold text-slate-800 text-[11px]">{t.category_name || 'General'}</div>
                      <div className="text-[10px] text-slate-500 line-clamp-2">{t.narration}</div>
                      {t.bill_no && (
                        <span className="inline-block mt-0.5 text-[9px] font-mono bg-slate-100 text-slate-600 px-1.5 py-0.2 rounded">
                          Bill: {t.bill_no}
                        </span>
                      )}
                    </td>
                    <td className="py-3 px-3 text-[11px]">
                      <div className="font-bold capitalize text-slate-800">{t.payment_mode}</div>
                      {t.payment_mode === 'cash' && t.cash_receiver_name && (
                        <div className="text-[10px] text-amber-900 bg-amber-50 px-1.5 py-0.5 rounded font-medium mt-0.5">
                          बुझ्ने: {t.cash_receiver_name} {t.cash_receiver_phone ? `(${t.cash_receiver_phone})` : ''}
                        </div>
                      )}
                      {t.payment_mode !== 'cash' && (t.cheque_no || t.bank_name) && (
                        <div className="text-[10px] text-blue-900 bg-blue-50 px-1.5 py-0.5 rounded font-mono mt-0.5">
                          {t.bank_name} {t.cheque_no ? `| Chq: ${t.cheque_no}` : ''}
                        </div>
                      )}
                    </td>
                    <td className="py-3 px-3 text-right font-mono font-black text-red-600">
                      {formatNPR(t.net_amount)}
                    </td>
                    <td className="py-3 px-3 text-right font-mono font-black text-slate-900">
                      {formatNPR(t.running_spent)}
                    </td>
                  </tr>
                ))}
                {(!siteLedger?.transactions || siteLedger.transactions.length === 0) && (
                  <tr>
                    <td colSpan="8" className="py-12 text-center text-slate-400">
                      No ledger transactions recorded for this site yet.
                    </td>
                  </tr>
                )}
              </tbody>
              <tfoot>
                <tr className="bg-slate-100 border-t-2 border-slate-300 font-black text-xs">
                  <td colSpan={6} className="py-3 px-3 text-right uppercase tracking-wider text-slate-700">
                    हालसम्मको कुल खर्च (Total Site Expense):
                  </td>
                  <td className="py-3 px-3 text-right font-mono text-red-700 text-sm">
                    {formatNPR(siteLedger?.summary?.total_expense || spent)}
                  </td>
                  <td className="py-3 px-3 text-right font-mono text-slate-900 text-sm">
                    {formatNPR(siteLedger?.summary?.total_expense || spent)}
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      )}

      {/* Tab: Overview */}
      {activeTab === 'overview' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-white rounded-3xl border border-slate-200/90 shadow-xs p-6 space-y-4">
            <h4 className="font-bold text-slate-900 text-xs uppercase tracking-wide border-b border-slate-100 pb-2">
              Site & Client Information
            </h4>
            <div className="space-y-2.5 text-xs text-slate-700">
              <div className="flex justify-between">
                <span className="text-slate-500">Site Location:</span>
                <span className="font-bold text-slate-900">{project.site_address}, {project.site_district}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Main Client:</span>
                <span className="font-bold text-slate-900">{project.main_client_name || 'Self / Internal'}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Client Phone:</span>
                <span className="font-mono text-slate-900">{project.main_client_phone || '—'}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Start Date (वि.सं.):</span>
                <span className="font-mono font-bold text-slate-900">{project.start_date_bs} BS</span>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-3xl border border-slate-200/90 shadow-xs p-6 space-y-4">
            <h4 className="font-bold text-slate-900 text-xs uppercase tracking-wide border-b border-slate-100 pb-2">
              Category-wise Expense Breakdown
            </h4>
            <div className="space-y-2 text-xs">
              {summary?.categoryBreakdown?.map((cat, idx) => (
                <div key={idx} className="flex justify-between py-1.5 border-b border-slate-100 text-[11px]">
                  <span className="text-slate-600 font-medium">{cat.category_name}</span>
                  <span className="font-mono font-bold text-slate-900">{formatNPR(cat.total)}</span>
                </div>
              ))}
              {(!summary?.categoryBreakdown || summary.categoryBreakdown.length === 0) && (
                <p className="text-slate-400 text-center py-4 text-xs">No expenses categorized yet.</p>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Print Signature Section */}
      <div className="hidden print:grid grid-cols-3 gap-6 pt-16 text-center text-xs font-bold text-slate-800 border-t-2 border-slate-800 mt-8">
        <div>
          <div className="border-b border-slate-400 mb-2 pb-6" />
          <span>साइट इन्जिनियर (Site Engineer)</span>
        </div>
        <div>
          <div className="border-b border-slate-400 mb-2 pb-6" />
          <span>लेखा शाखा (Accounts Officer)</span>
        </div>
        <div>
          <div className="border-b border-slate-400 mb-2 pb-6" />
          <span>प्रबन्ध निर्देशक (Managing Director)</span>
        </div>
      </div>

      {/* Edit Site Modal */}
      {isEditModalOpen && editForm && (
        <Modal
          isOpen={isEditModalOpen}
          onClose={() => setIsEditModalOpen(false)}
          title={`साइट सम्पादन — ${project.project_code}`}
          size="lg"
        >
          <form onSubmit={handleSaveEdit} className="space-y-4 text-xs">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block font-bold text-slate-700 mb-1">साइटको नाम (Site Name) *</label>
                <input
                  type="text"
                  required
                  value={editForm.project_name}
                  onChange={(e) => setEditForm({ ...editForm, project_name: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-200 rounded-xl font-medium"
                />
              </div>

              <div>
                <label className="block font-bold text-slate-700 mb-1">साइटको प्रकार (Site Type) *</label>
                <select
                  value={editForm.project_type}
                  onChange={(e) => setEditForm({ ...editForm, project_type: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-200 rounded-xl bg-white font-bold"
                >
                  <option value="solo">🏛️ Solo Site (100% R.P. Builders)</option>
                  <option value="joint_venture">🤝 Joint Venture (JV)</option>
                </select>
              </div>
            </div>

            {/* JV Fields */}
            {editForm.project_type === 'joint_venture' && (
              <div className="p-4 bg-purple-50/70 border border-purple-200 rounded-2xl space-y-3">
                <span className="font-bold text-purple-900 block">Joint Venture (JV) विवरण</span>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  <div>
                    <label className="block font-semibold text-purple-900 mb-1">पार्टनर कम्पनीको नाम *</label>
                    <input
                      type="text"
                      required={editForm.project_type === 'joint_venture'}
                      value={editForm.partner_company_name}
                      onChange={(e) => setEditForm({ ...editForm, partner_company_name: e.target.value })}
                      placeholder="e.g. ABC Construction"
                      className="w-full px-3 py-2 border border-purple-200 rounded-xl bg-white"
                    />
                  </div>
                  <div>
                    <label className="block font-semibold text-purple-900 mb-1">RP Builders शेयर %</label>
                    <input
                      type="number"
                      value={editForm.rp_share_percent}
                      onChange={(e) => {
                        const rp = parseFloat(e.target.value) || 0;
                        setEditForm({
                          ...editForm,
                          rp_share_percent: e.target.value,
                          partner_share_percent: String(Math.max(0, 100 - rp))
                        });
                      }}
                      className="w-full px-3 py-2 border border-purple-200 rounded-xl bg-white font-mono font-bold"
                    />
                  </div>
                  <div>
                    <label className="block font-semibold text-purple-900 mb-1">Partner शेयर %</label>
                    <input
                      type="number"
                      value={editForm.partner_share_percent}
                      onChange={(e) => {
                        const pt = parseFloat(e.target.value) || 0;
                        setEditForm({
                          ...editForm,
                          partner_share_percent: e.target.value,
                          rp_share_percent: String(Math.max(0, 100 - pt))
                        });
                      }}
                      className="w-full px-3 py-2 border border-purple-200 rounded-xl bg-white font-mono font-bold"
                    />
                  </div>
                </div>
              </div>
            )}

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block font-bold text-slate-700 mb-1">स्वीकृत बजेट (Estimated Budget NPR)</label>
                <input
                  type="number"
                  value={editForm.budget_total}
                  onChange={(e) => setEditForm({ ...editForm, budget_total: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-200 rounded-xl font-mono"
                />
              </div>

              <div>
                <label className="block font-bold text-slate-700 mb-1">ठेक्का रकम (Contract Value NPR)</label>
                <input
                  type="number"
                  value={editForm.contract_value}
                  onChange={(e) => setEditForm({ ...editForm, contract_value: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-200 rounded-xl font-mono"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block font-bold text-slate-700 mb-1">साइट ठेगाना (Location)</label>
                <input
                  type="text"
                  value={editForm.site_address}
                  onChange={(e) => setEditForm({ ...editForm, site_address: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-200 rounded-xl"
                />
              </div>

              <div>
                <label className="block font-bold text-slate-700 mb-1">जिल्ला (District)</label>
                <input
                  type="text"
                  value={editForm.site_district}
                  onChange={(e) => setEditForm({ ...editForm, site_district: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-200 rounded-xl"
                />
              </div>

              <div>
                <label className="block font-bold text-slate-700 mb-1">अवस्था (Status)</label>
                <select
                  value={editForm.status}
                  onChange={(e) => setEditForm({ ...editForm, status: e.target.value })}
                  className="w-full px-3 py-2 border border-slate-200 rounded-xl bg-white font-bold capitalize"
                >
                  <option value="active">Active (सञ्चालनमा)</option>
                  <option value="completed">Completed (सम्पन्न)</option>
                  <option value="on_hold">On Hold (स्थगित)</option>
                  <option value="planned">Planned (योजना)</option>
                </select>
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-4 border-t border-slate-100">
              <button
                type="button"
                onClick={() => setIsEditModalOpen(false)}
                className="px-4 py-2 border border-slate-200 rounded-xl text-slate-600 hover:bg-slate-100 font-bold"
              >
                रद्द गर्नुहोस् (Cancel)
              </button>
              <button
                type="submit"
                disabled={savingEdit}
                className="px-5 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-bold shadow-sm"
              >
                {savingEdit ? 'सुरक्षित गर्दै...' : 'विवरण परिवर्तन गर्नुहोस् (Save Changes)'}
              </button>
            </div>
          </form>
        </Modal>
      )}
    </div>
  );
}
